### ISSUE TITLE
How is this applied in the context of conformal flows?

### ISSUE THREAD

**Issue by qingfengxulai199** [rubenwiersma/gravo-mg#2]
I apologize for the interruption. I am currently studying topics related to multigrid methods and conformal flows. I have read your article published this year titled "A Fast Geometric Multigrid Method for Curved Surfaces". I'd like to inquire about how the Gravo MG is applied in conformal flows and what specific problems related to conformal flows it addresses. I appreciate your response despite your busy schedule. Thank you.

**Comment by rubenwiersma** [comment]
One step in computing conformal flows is solving a linear system, which is updated every step of the flow (the mass matrix is updated). Because the linear system changes every step, you cannot reuse a factorization of the linear system, which makes the task expensive for typical solvers (e.g. Cholesky - Eigen and Paradiso in the paper). A multigrid method (Section 3) can be faster in this setting, since the construction of the hierarchy can be reused and is often faster to compute than the factorization of the matrix, even though the solver part is slower (see table 4). Gravo MG is a fast way to construct such a hierarchy. This hierarchy can then be used to solve the linear systems that arise in conformal flows.
